"""Mathematical structure type system.

Math-anything 的核心命题：物理、化学、力学、材料科学
不是独立学科，而是对同一组数学结构的不同实例化。

本模块定义这些结构的抽象类型层次。
"""

from .algebras import (
    ClassicalState,
    CommutativeCase,
    CStarAlgebra,
    GNSConstruction,
    NoncommutativeProbability,
    PureState,
    QuantumState,
    StarAlgebra,
    State,
    TomitaTakesakiTheory,
    VonNeumannAlgebra,
)
from .analysis import (
    AlgebraicConvergence,
    APosterioriEstimate,
    APrioriEstimate,
    CFL_Condition,
    ConsistencyCondition,
    ConvergenceOrder,
    EnergyStability,
    ErrorEstimate,
    ExponentialConvergence,
    GeneralCFL,
    HyperbolicCFL,
    LaxEquivalenceTheorem,
    LaxRichtmyerStability,
    NumericalAnalysis,
    ParabolicCFL,
    StabilityCondition,
    SublinearConvergence,
    SuperconvergenceEstimate,
    VonNeumannStability,
)
from .base import AbstractMathematicalStructure
from .category_theory import (
    Adjunction,
    Category,
    Equalizer,
    Functor,
    KanExtension,
    Limit,
    Monad,
    NaturalTransformation,
    Product,
    Pullback,
)
from .conservation_field import (
    NOETHER_CORRESPONDENCE,
    ConservationMatrixField,
    FieldConservedQuantity,
    NoetherCurrent,
)
from .coupled import (
    BidirectionalCoupling,
    CoupledSystem,
    MultiphysicsCoupling,
    MultiscaleCoupling,
    SequentialCoupling,
)
from .ensemble import (
    BayesianInferenceProblem,
    EnsembleProblem,
    EquilibriumEnsemble,
    KineticProcess,
)
from .equilibrium import (
    ConstrainedMinimizationProblem,
    EquilibriumProblem,
    FixedPointProblem,
    VariationalMinimizationProblem,
)
from .evolution import (
    ConservationLawSystem,
    ConservedQuantity,
    DissipativeSystem,
    EvolutionProblem,
    FluxType,
    HamiltonianSystem,
    NavierStokesProblem,
    NSRegime,
    NSTurbulenceModel,
    StochasticSystem,
)
from .geometry import (
    Connection,
    CovectorField,
    Curvature,
    DeformationMapping,
    GreenLagrangeStrain,
    LeviCivitaConnection,
    LieDerivative,
    Metric,
    PolarDecomposition,
    RicciCurvature,
    RiemannCurvature,
    RightCauchyGreen,
    ScalarCurvature,
    SmoothManifold,
    TangentBundle,
    TensorField,
    VectorField,
)
from .neural_network import (
    ActivationMorphism,
    LinearMorphism,
    LossMorphism,
)
from .groups import (
    BandCompatibility,
    BandStructureAnalysis,
    CharacterTable,
    ClebschGordanCoefficients,
    DirectProductDecomposition,
    FiniteGroupRepresentation,
    GroupRepresentation,
    IrreducibleRepresentation,
    SelectionRules,
    SpaceGroupRepresentation,
    WignerEckartTheorem,
    character_table_c2v,
    character_table_d2h,
    character_table_oh,
    character_table_td,
)
from .properties import (
    OperatorType,
    StructuralInvariant,
    StructuralProperty,
    StructureDomain,
    SymmetryGroup,
)
from .spectral import (
    LinearEigenvalueProblem,
    NonlinearEigenvalueProblem,
    SelfConsistentProblem,
    SpectralProblem,
)

__all__ = [
    "AbstractMathematicalStructure",
    "StructuralProperty",
    "StructuralInvariant",
    "OperatorType",
    "StructureDomain",
    "SymmetryGroup",
    "SpectralProblem",
    "LinearEigenvalueProblem",
    "NonlinearEigenvalueProblem",
    "SelfConsistentProblem",
    "EvolutionProblem",
    "HamiltonianSystem",
    "ConservationLawSystem",
    "DissipativeSystem",
    "StochasticSystem",
    "EquilibriumProblem",
    "VariationalMinimizationProblem",
    "ConstrainedMinimizationProblem",
    "FixedPointProblem",
    "CoupledSystem",
    "SequentialCoupling",
    "BidirectionalCoupling",
    "MultiscaleCoupling",
    "MultiphysicsCoupling",
    "EnsembleProblem",
    "EquilibriumEnsemble",
    "KineticProcess",
    "BayesianInferenceProblem",
    "SmoothManifold",
    "TangentBundle",
    "VectorField",
    "CovectorField",
    "TensorField",
    "Metric",
    "Connection",
    "LeviCivitaConnection",
    "Curvature",
    "RiemannCurvature",
    "RicciCurvature",
    "ScalarCurvature",
    "LieDerivative",
    "DeformationMapping",
    "RightCauchyGreen",
    "GreenLagrangeStrain",
    "PolarDecomposition",
    # Neural-network morphisms
    "LinearMorphism",
    "ActivationMorphism",
    "LossMorphism",
    "StarAlgebra",
    "CStarAlgebra",
    "VonNeumannAlgebra",
    "State",
    "ClassicalState",
    "QuantumState",
    "PureState",
    "GNSConstruction",
    "CommutativeCase",
    "TomitaTakesakiTheory",
    "NoncommutativeProbability",
    # Numerical Analysis
    "NumericalAnalysis",
    "ConsistencyCondition",
    "StabilityCondition",
    "VonNeumannStability",
    "EnergyStability",
    "LaxRichtmyerStability",
    "LaxEquivalenceTheorem",
    "ErrorEstimate",
    "APrioriEstimate",
    "APosterioriEstimate",
    "SuperconvergenceEstimate",
    "CFL_Condition",
    "HyperbolicCFL",
    "ParabolicCFL",
    "GeneralCFL",
    "ConvergenceOrder",
    "AlgebraicConvergence",
    "ExponentialConvergence",
    "SublinearConvergence",
    # Group Theory
    "GroupRepresentation",
    "FiniteGroupRepresentation",
    "IrreducibleRepresentation",
    "DirectProductDecomposition",
    "WignerEckartTheorem",
    "SpaceGroupRepresentation",
    "BandCompatibility",
    "SelectionRules",
    "CharacterTable",
    "ClebschGordanCoefficients",
    "BandStructureAnalysis",
    "character_table_c2v",
    "character_table_d2h",
    "character_table_oh",
    "character_table_td",
    # Category Theory
    "Category",
    "Functor",
    "NaturalTransformation",
    "Adjunction",
    "Monad",
    "Limit",
    "Product",
    "Pullback",
    "Equalizer",
    "KanExtension",
    # Conservation Field
    "ConservationMatrixField",
    "FieldConservedQuantity",
    "NoetherCurrent",
    "NOETHER_CORRESPONDENCE",
]
