"""Bourbaki Foundation Layer — algorithms and formal systems.

The foundation layer provides the mathematical machinery that underlies
all domain instantiations:

  - categories:   Category-theoretic reasoning + knowledge graph
  - constraints:  Learnable invariants, propagation, boundary evolution
  - type_theory:  MLTT / CIC / HoTT type system (3-layer architecture)
  - dimensional:  Buckingham π theorem, dimensional analysis
  - symbolic:     EML symbolic regression, expression discovery
"""

# ── Category Theory ──
from math_anything.categories import (
    CategoryEngine,
    GraphQueryEngine,
    KnowledgeGraphBuilder,
    MathKnowledgeGraph,
    MorphismLink,
)

# ── Constraint System ──
from math_anything.constraints import (
    BoundaryEvolution,
    BoundaryState,
    ConstraintPropagation,
    DomainCondition,
    DomainHypothesis,
    DomainLearner,
    ExecutionRecord,
    InvariantStatus,
    LearnedInvariant,
    PropagationChain,
    PropagationOutcome,
    PropagationResult,
    RiskItem,
    TrainingExample,
    WeakeningRule,
    from_structural_invariant,
)

# ── Dimensional Analysis ──
from math_anything.dimensional import (
    BASE_DIMENSIONS,
    BUILTIN_QUANTITIES,
    NAMED_PI_GROUPS,
    BuckinghamPiEngine,
    BuckinghamPiGroup,
    EquationChecker,
    EquationDimensionalCheck,
    FluidDimensionAnalyzer,
    PhysicalQuantity,
    QMDimensionAnalyzer,
    TermDimension,
)

# ── Symbolic Regression (lazy — delegates to eml_v2) ──
from math_anything.eml_v2 import (
    ExprBuilder,
    ImprovedSymbolicRegression,
    Node,
    NodeType,
    SymbolicRegression,
    discover_equation,
    eml,
)

# ── Type Theory (3-layer) ──
from math_anything.type_theory import (
    BOOL_TYPE,
    CIRCLE,
    GODEL_BOUNDARIES,
    INTERVAL,
    NAT_TYPE,
    PROP,
    TORUS,
    TYPE0,
    TYPE0_SORT,
    TYPE1,
    TYPE1_SORT,
    UNDECIDABILITY_RESULTS,
    Annotation,
    App,
    CICBridge,
    CICTypeChecker,
    CoConstructor,
    CoFix,
    CoInductiveType,
    CoMatch,
    Cong,
    Construct,
    Constructor,
    Context,
    DecidabilityBoundary,
    DecidabilityClass,
    Equivalence,
    Fiber,
    Fixpoint,
    FormalSystemStrength,
    GodelBoundary,
    HigherInductiveType,
    HITElim,
    # HoTT (Layer 3)
    HLevel,
    HoTTBridge,
    HoTTTypeChecker,
    Identity,
    IdToEquiv,
    IndElim,
    InductiveFamily,
    InductiveType,
    IsHLevel,
    Judgment,
    Lam,
    MetamathAnalyzer,
    MorphismType,
    Pair,
    PathConstructor,
    Pi,
    Proj1,
    Proj2,
    PropTypeRule,
    QuotientIntro,
    QuotientLift,
    QuotientType,
    Refl,
    Sigma,
    Sort,
    # CIC (Layer 2)
    SortKind,
    Sym,
    # MLTT (Layer 1)
    Term,
    TerminationCheck,
    TermKind,
    Trans,
    Transport,
    TypeChecker,
    TypeCheckError,
    TypeCheckResult,
    TypeTheoryBridge,
    Univalence,
    Universe,
    Var,
    arrow,
    check_termination,
    free_vars,
    invariant_to_identity,
    invariant_to_prop_type,
    morphism_to_type,
    product,
    propagation_to_transport,
    structure_to_inductive,
    substitute,
    term_to_str,
    whnf,
)

__all__ = [
    # Category Theory
    "CategoryEngine",
    "MorphismLink",
    "MathKnowledgeGraph",
    "KnowledgeGraphBuilder",
    "GraphQueryEngine",
    # Constraint System
    "LearnedInvariant",
    "InvariantStatus",
    "PropagationOutcome",
    "WeakeningRule",
    "DomainCondition",
    "from_structural_invariant",
    "ConstraintPropagation",
    "PropagationResult",
    "PropagationChain",
    "BoundaryState",
    "BoundaryEvolution",
    "ExecutionRecord",
    "RiskItem",
    "DomainLearner",
    "DomainHypothesis",
    "TrainingExample",
    # Type Theory — MLTT
    "Term",
    "TermKind",
    "Var",
    "Universe",
    "Pi",
    "Lam",
    "App",
    "Sigma",
    "Pair",
    "Proj1",
    "Proj2",
    "Identity",
    "Refl",
    "Sym",
    "Trans",
    "Cong",
    "Transport",
    "Annotation",
    "InductiveType",
    "Constructor",
    "Construct",
    "IndElim",
    "Context",
    "Judgment",
    "free_vars",
    "substitute",
    "whnf",
    "term_to_str",
    "arrow",
    "product",
    "TYPE0",
    "TYPE1",
    "BOOL_TYPE",
    "NAT_TYPE",
    "TypeChecker",
    "TypeCheckResult",
    "TypeCheckError",
    "TypeTheoryBridge",
    "MorphismType",
    "invariant_to_identity",
    "invariant_to_prop_type",
    "morphism_to_type",
    "propagation_to_transport",
    "structure_to_inductive",
    "FormalSystemStrength",
    "DecidabilityClass",
    "GodelBoundary",
    "DecidabilityBoundary",
    "MetamathAnalyzer",
    "UNDECIDABILITY_RESULTS",
    "GODEL_BOUNDARIES",
    # Type Theory — CIC
    "SortKind",
    "Sort",
    "PROP",
    "TYPE0_SORT",
    "TYPE1_SORT",
    "PropTypeRule",
    "CoConstructor",
    "CoInductiveType",
    "CoFix",
    "CoMatch",
    "QuotientType",
    "QuotientIntro",
    "QuotientLift",
    "Fixpoint",
    "TerminationCheck",
    "check_termination",
    "InductiveFamily",
    "CICTypeChecker",
    "CICBridge",
    # Type Theory — HoTT
    "HLevel",
    "IsHLevel",
    "Equivalence",
    "Univalence",
    "IdToEquiv",
    "PathConstructor",
    "HigherInductiveType",
    "HITElim",
    "Fiber",
    "HoTTTypeChecker",
    "HoTTBridge",
    "INTERVAL",
    "CIRCLE",
    "TORUS",
    # Dimensional Analysis
    "BASE_DIMENSIONS",
    "BUILTIN_QUANTITIES",
    "BuckinghamPiEngine",
    "BuckinghamPiGroup",
    "PhysicalQuantity",
    "NAMED_PI_GROUPS",
    "FluidDimensionAnalyzer",
    "QMDimensionAnalyzer",
    "EquationChecker",
    "EquationDimensionalCheck",
    "TermDimension",
    # Symbolic Regression
    "NodeType",
    "Node",
    "ExprBuilder",
    "ImprovedSymbolicRegression",
    "SymbolicRegression",
    "discover_equation",
    "eml",
]
